// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDxdlaTcY4je80X7dZRL-NSOIYl1Szw-A',
    appId: '1:1006010960150:web:6c28b852936581dbf8a837',
    messagingSenderId: '1006010960150',
    projectId: 'socialapptutorial-8ca57',
    authDomain: 'socialapptutorial-8ca57.firebaseapp.com',
    storageBucket: 'socialapptutorial-8ca57.firebasestorage.app',
    measurementId: 'G-MYSRG3WDMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC22lixCzsyvqW-gnT6fG25KCsvJV-HnJQ',
    appId: '1:1006010960150:android:1bb655b231f8f63af8a837',
    messagingSenderId: '1006010960150',
    projectId: 'socialapptutorial-8ca57',
    storageBucket: 'socialapptutorial-8ca57.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqEJ4iO_IM2oCtFiqLdC0lCaEU0WHQh0E',
    appId: '1:1006010960150:ios:98429d65afc99652f8a837',
    messagingSenderId: '1006010960150',
    projectId: 'socialapptutorial-8ca57',
    storageBucket: 'socialapptutorial-8ca57.firebasestorage.app',
    iosBundleId: 'com.example.blocCleanArchitecture',
  );
}
